# Generated by Django 2.2.1 on 2019-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_add_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='no_fee_listing',
            field=models.BooleanField(default=False, help_text='Only check if OP is 100%'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('not_approved', 'Not Approved')], default='draft', max_length=50),
        ),
    ]
