# Generated by Django 2.2.1 on 2019-05-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_add_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='agent_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
