# Generated by Django 2.2.1 on 2019-05-29 17:22

from django.db import migrations, models
import penny.utils


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190521_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to=penny.utils.image_path, validators=[penny.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='listingphotos',
            name='primary_photo',
            field=models.ImageField(blank=True, null=True, upload_to=penny.utils.image_path, validators=[penny.utils.validate_file_size]),
        ),
    ]
