# Generated by Django 2.2.1 on 2019-06-29 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190529_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bikability_score',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='nearby_transit',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.CharField(choices=[('dedicated_reserved_spot', 'Dedicated reserved spot'), ('shared_street_permit_parking', 'Shared street permit parking'), ('shared_public_street_parking', 'Shared public street parking'), (' no_parking_available', ' No parking available')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='walkability_score',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
