# Generated by Django 2.2.2 on 2019-06-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190629_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.CharField(choices=[('dedicated_reserved_spot', 'Dedicated reserved spot'), ('shared_street_permit_parking', 'Shared street permit parking'), ('shared_public_street_parking', 'Shared public street parking'), ('no_parking_available', 'No parking available')], max_length=255, null=True),
        ),
    ]
