# Generated by Django 2.2.3 on 2019-07-24 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190724_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bikeability_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='nearby_transit',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.CharField(blank=True, choices=[('dedicated_reserved_spot', 'Dedicated reserved spot'), ('shared_street_permit_parking', 'Shared street permit parking'), ('shared_public_street_parking', 'Shared public street parking'), ('no_parking_available', 'No parking available')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='walkability_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
