# Generated by Django 2.2.4 on 2019-08-12 18:29

from django.db import migrations
import optimized_image.fields
import penny.utils


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20190729_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingphoto',
            name='photo',
            field=optimized_image.fields.OptimizedImageField(blank=True, upload_to=penny.utils.image_path),
        ),
        migrations.AlterField(
            model_name='listingphotos',
            name='primary_photo',
            field=optimized_image.fields.OptimizedImageField(blank=True, null=True, upload_to=penny.utils.image_path),
        ),
    ]
