# Generated by Django 2.2.4 on 2020-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20190812_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('commercial', 'Commercial')], max_length=255, verbose_name='Type'),
        ),
    ]
