# Generated by Django 2.2.4 on 2020-07-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20200717_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='sales_agent',
        ),
    ]
