# Generated by Django 2.2.4 on 2020-07-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_listing_sales_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingdetail',
            name='listing_agreement',
        ),
    ]
