# Generated by Django 2.2.4 on 2020-07-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_remove_listingdetail_listing_agreement'),
        ('listings', '0013_auto_20200723_1739'),
    ]

    operations = [
    ]
