# Generated by Django 2.2.4 on 2020-07-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_merge_20200727_2140'),
        ('listings', '0015_merge_20200727_2200'),
    ]

    operations = [
    ]
