# Generated by Django 2.2.4 on 2020-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_merge_20200727_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.PositiveSmallIntegerField(help_text='sq.feet', null=True),
        ),
    ]
