# Generated by Django 2.2.4 on 2020-08-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_merge_20200728_1632'),
        ('listings', '0016_auto_20200813_1919'),
    ]

    operations = [
    ]
