# Generated by Django 2.2.4 on 2020-08-20 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_merge_20200813_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('dyre_avenue_line', 'Dyre Avenue Line (Bronx) 5'), ('jerome_avenue_line', 'Jerome Avenue Line (Bronx) 4 5'), ('pelham_line', 'Pelham Line (Bronx) 6'), ('white_plains_road_line', 'White Plains Road Line (Bronx) 2 5'), ('concourse_line', 'Concourse Line (Bronx Manhattan) B D'), ('broadway_seventh_avenue', 'Broadway–Seventh Avenue Line (Bronx Manhattan Brooklyn) 1 2 3'), ('fourth_avenue_line', 'Fourth Avenue Line (Brooklyn) D N R W'), ('brighton_line', 'Brighton Line (Brooklyn) B Q'), ('culver_line', 'Culver Line (Brooklyn) F G'), ('eastern_parkway_line', 'Eastern Parkway Line (Brooklyn) 2 3 4 5'), ('franklin_avenue_line', 'Franklin Avenue Line (Brooklyn) S'), ('new_lots_line', 'New Lots Line Line (Brooklyn) 2 3 4 5'), ('nostrand_avenue_line', 'Nostrand Avenue Line Line (Brooklyn) 2 5'), ('sea_beach_line', 'Sea Beach Line (Brooklyn) N W'), ('west_end_line', 'West End Line (Brooklyn) D'), ('crosstown_line', 'Crosstown Line (Brooklyn Queens) G'), ('fulton_street_line', 'Fulton Street Line (Brooklyn Queens) A C'), ('jamaica_line', 'Jamaica Line (Brooklyn Queens) J M Z'), ('myrtle_avenue_line', 'Myrtle Avenue Line (Brooklyn Queens) M'), ('second_avenue_line', 'Second Avenue Line (Manhattan) N Q R'), ('42nd_street_shuttle', '42nd Street Shuttle (Manhattan) S'), ('63rd_street_line', '63rd Street Line (Manhattan) N Q R'), ('broadway_line', 'Broadway Line (Manhattan) N Q R W'), ('lenox_avenue_line', 'Lenox Avenue Line (Manhattan) 2 3'), ('lexington_avenue_line', 'Lexington Avenue Line (Manhattan) 5 4 6'), ('nassau_street_line', 'Nassau Street Line (Manhattan) K M Z'), ('sixth_avenue_line', 'Sixth Avenue Line (Manhattan Brooklyn) B D F M'), ('eighth_avenue_line', 'Eighth Avenue Line (Manhattan Brooklyn) A B C D E'), ('canarsie_line', 'Canarsie Line (Manhattan Brooklyn) L'), ('63rd_street_line', '63rd Street Line (Manhattan Queens) F'), ('flushing_line', 'Flushing Line (Manhattan Queens) 7'), ('queens_boulevard_line', 'Queens Boulevard Line (Manhattan Queens) E F M R'), ('archer_avenue_line', 'Archer Avenue Line (Queens) J Z'), ('archer_avenue_line_e', 'Archer Avenue Line E (Queens) E'), ('astoria_line', 'Astoria Line (Queens) N W'), ('rockaway_line', '\tRockaway Line (Queens) A S')], max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='choices_nearby_transit',
            field=models.ManyToManyField(to='listings.TransitOptions', verbose_name='Other transit options'),
        ),
    ]
