# Generated by Django 2.2.4 on 2020-08-18 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_merge_20200813_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('dyre_avenue_line', 'Dyre Avenue Line (Bronx)'), ('jerome_avenue_line', 'Jerome Avenue Line (Bronx)'), ('pelham_line', 'Pelham Line (Bronx)'), ('white_plains_road_line', 'White Plains Road Line (Bronx)'), ('concourse_line', 'Concourse Line (Bronx Manhattan'), ('broadway_seventh_avenue', 'Broadway–Seventh Avenue Line (Bronx Manhattan Brooklyn)'), ('fourth_avenue_line', 'Fourth Avenue Line (Brooklyn)'), ('brighton_line', 'Brighton Line (Brooklyn)'), ('culver_line', 'Culver Line (Brooklyn)'), ('eastern_parkway_line', 'Eastern Parkway Line (Brooklyn)'), ('franklin_avenue_line', 'Franklin Avenue Line (Brooklyn)'), ('new_lots_line', 'New Lots Line Line (Brooklyn)'), ('nostrand_avenue_line', 'Nostrand Avenue Line Line (Brooklyn)'), ('sea_beach_line', 'Sea Beach Line (Brooklyn)'), ('west_end_line', 'West End Line (Brooklyn)'), ('crosstown_line', 'Crosstown Line (Brooklyn Queens)'), ('fulton_street_line', 'Fulton Street Line (Brooklyn Queens)'), ('jamaica_line', 'Jamaica Line (Brooklyn Queens)'), ('myrtle_avenue_line', 'Myrtle Avenue Line (Brooklyn Queens)'), ('42nd_street_shuttle', '42nd Street Shuttle (Manhattan)'), ('63rd_street_line', '63rd Street Line (Manhattan)'), ('broadway_line', 'Broadway Line (Manhattan)'), ('lenox_avenue_line', 'Lenox Avenue Line (Manhattan)'), ('lexington_avenue_line', 'Lexington Avenue Line (Manhattan)'), ('nassau_street_line', 'Nassau Street Line (Manhattan)'), ('sixth_avenue_line', 'Sixth Avenue Line (Manhattan Brooklyn)'), ('eighth_avenue_line', 'Eighth Avenue Line (Manhattan Brooklyn)'), ('canarsie_line', 'Canarsie Line (Manhattan Brooklyn)'), ('63rd_street_line', '63rd Street Line (Manhattan Queens)'), ('flushing_line', 'Flushing Line (Manhattan Queens)'), ('queens_boulevard_line', 'Queens Boulevard Line (Manhattan Queens)'), ('archer_avenue_line', 'Archer Avenue Line (Queens)'), ('archer_avenue_line_e', 'Archer Avenue Line E (Queens)'), ('astoria_line', 'Astoria Line (Queens)'), ('rockaway_line', '\tRockaway Line (Queens)')], max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='other_nearby_transit',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='nearby_transit',
        ),
        migrations.AddField(
            model_name='listing',
            name='nearby_transit',
            field=models.ManyToManyField(to='listings.TransitOptions'),
        ),
    ]
