# Generated by Django 2.2 on 2019-04-25 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rentproperty_is_listed'),
        ('penny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('radius', models.PositiveIntegerField(default=1000)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reference_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.RentProperty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
