# Generated by Django 2.2.1 on 2019-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penny', '0003_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('client', 'Client')], default='agent', max_length=255),
            preserve_default=False,
        ),
    ]
