# Generated by Django 2.2.1 on 2019-05-10 19:08

from django.db import migrations
import penny.models


class Migration(migrations.Migration):

    dependencies = [
        ('penny', '0005_delete_availability'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', penny.models.UserTypeManager()),
            ],
        ),
    ]
