# Generated by Django 2.2.1 on 2019-06-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
        ('penny', '0007_auto_20190621_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_applications.JobApplication'),
        ),
    ]
