# Generated by Django 2.2.3 on 2019-07-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penny', '0008_user_job_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('agent', 'Agent'), ('client', 'Client'), ('admin', 'Admin')], max_length=255),
        ),
    ]
