# Generated by Django 2.2.3 on 2019-07-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penny', '0009_auto_20190708_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_applications.JobApplication'),
        ),
    ]
