# Generated by Django 2.2.4 on 2019-08-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penny', '0010_auto_20190724_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
