# Generated by Django 2.2 on 2019-04-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproperty',
            name='geopoint',
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
