# Generated by Django 2.2 on 2019-04-20 00:23

from django.db import migrations


def geopoint_from_latlon(apps, schema_editor):
    RentProperty = apps.get_model('rentals', 'RentProperty')

    for rp in RentProperty.objects.all():
        rp.geopoint = f"POINT ({rp.longitude} {rp.latitude})"
        rp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rentproperty_geopoint'),
    ]

    operations = [
        migrations.RunPython(geopoint_from_latlon),
    ]
