# Generated by Django 2.2 on 2019-04-20 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_populate_geopoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentproperty',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='longitude',
        ),
    ]
