# Generated by Django 2.2 on 2019-04-22 03:46

from django.db import migrations, models
import django.db.models.deletion
import penny.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20190420_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=penny.utils.image_path, validators=[penny.utils.validate_file_size])),
                ('rent_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.RentProperty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
