# Generated by Django 2.2 on 2019-04-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rentpropertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentproperty',
            name='about',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='amenities',
            field=models.CharField(max_length=255),
        ),
    ]
