# Generated by Django 2.2 on 2019-04-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rentpropertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproperty',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
