DEFAUL_RENT_IMAGE = 'images/no-image.png'
DEFAUL_AVATAR = 'images/blank-profile-picture.png'

MANHATTAN_NEIGHBORHOODS = (
    ('alphabet_city', 'Alphabet City'),
    ('battery_park_city', 'Battery Park City'),
    ('carnegie_hill', 'Carnegie Hill'),
    ('chelsea', 'Chelsea'),
    ('chinatown', 'Chinatown'),
    ('east_harlem', 'East Harlem'),
    ('east_village', 'East Village'),
    ('financial_district', 'Financial District'),
    ('flatiron_district', 'Flatiron District'),
    ('gramercy_park', 'Gramercy Park'),
    ('greenwich_village', 'Greenwich Village'),
    ('harlem', 'Harlem'),
    ('hells_kitchen', 'Hell\'s Kitchen/Clinton'),
    ('inwood', 'Inwood'),
    ('kips_bay', 'Kips Bay'),
    ('lincoln_square', 'Lincoln Square'),
    ('lower_east_side', 'Lower East Side'),
    ('manhattan_valley', 'Manhattan Valley'),
    ('midtown_east', 'Midtown East'),
    ('midtown_west', 'Midtown West'),
    ('morningside_heights', 'Morningside Heights'),
    ('murray_hill', 'Murray Hill'),
    ('nolita/little_italy', 'NoLita/Little Italy'),
    ('roosevelt_island', 'Roosevelt Island'),
    ('soho', 'SoHo'),
    ('tribeca', 'Tribeca'),
    ('upper_east_side', 'Upper East Side'),
    ('upper_west_side', 'Upper West Side'),
    ('washington_heights', 'Washington Heights'),
    ('west_village', 'West Village'),
)

BRONX_NEIGHBORHOODS = (
    ('baychester', 'Baychester/Co-op City'),
    ('bedford_park', 'Bedford Park'),
    ('belmont', 'Belmont'),
    ('bronxdale', 'Bronxdale'),
    ('castle_hill', 'Castle Hill'),
    ('city_island', 'City Island'),
    ('concourse_village', 'Concourse Village/Grand Concourse/Morrisania'),
    ('country_club', 'Country Club'),
    ('fieldston', 'Fieldston'),
    ('fordham', 'Fordham'),
    ('hunts_point', 'Hunts Point'),
    ('kingsbridge', 'Kingsbridge'),
    ('kingsbridge_heights', 'Kingsbridge Heights'),
    ('melrose', 'Melrose'),
    ('morris_heights', 'Morris Heights'),
    ('morris_park', 'Morris Park'),
    ('mott_haven', 'Mott Haven'),
    ('parkchester', 'Parkchester'),
    ('pelham_bay', 'Pelham Bay'),
    ('pelham_gardens', 'Pelham Gardens'),
    ('pelham_parkway', 'Pelham Parkway'),
    ('port_morris', 'Port Morris'),
    ('riverdale', 'Riverdale'),
    ('soundview', 'Soundview'),
    ('throgs_neck', 'Throgs Neck'),
    ('tremont', 'Tremont'),
    ('university_heights', 'University Heights'),
    ('wakefield', 'Wakefield'),
    ('williamsbridge', 'Williamsbridge'),
    ('woodlawn', 'Woodlawn'),
)

QUEENS_NEIGHBORHOODS = (
    ('arverne', 'Arverne'),
    ('astoria', 'Astoria'),
    ('bayside', 'Bayside'),
    ('beechhurst', 'Beechhurst'),
    ('belle_harbor/neponsit', 'Belle Harbor/Neponsit'),
    ('bellerose', 'Bellerose'),
    ('briarwood', 'Briarwood'),
    ('broad_channel', 'Broad Channel'),
    ('cambria_heights', 'Cambria Heights'),
    ('college_point', 'College Point'),
    ('corona', 'Corona'),
    ('douglaston', 'Douglaston'),
    ('east_elmhurst', 'East Elmhurst'),
    ('elmhurst', 'Elmhurst'),
    ('far_rockaway', 'Far Rockaway'),
    ('floral_park', 'Floral Park'),
    ('flushing', 'Flushing'),
    ('forest_hills', 'Forest Hills'),
    ('fresh_meadows', 'Fresh Meadows'),
    ('glen_oaks', 'Glen Oaks'),
    ('glendale', 'Glendale'),
    ('hillcrest', 'Hillcrest'),
    ('hollis', 'Hollis'),
    ('hollis_hills', 'Hollis Hills'),
    ('howard_beach', 'Howard Beach'),
    ('jackson_heights', 'Jackson Heights'),
    ('jamaica', 'Jamaica'),
    ('jamaica_estates', 'Jamaica Estates'),
    ('jamaica_hills', 'Jamaica Hills'),
    ('kew_gardens', 'Kew Gardens'),
    ('laurelton', 'Laurelton'),
    ('little_neck', 'Little Neck'),
    ('long_island_city', 'Long Island City'),
    ('maspeth', 'Maspeth'),
    ('middle_village', 'Middle Village'),
    ('oakland_gardens', 'Oakland Gardens'),
    ('ozone_park', 'Ozone Park'),
    ('queens_village', 'Queens Village'),
    ('rego_park', 'Rego Park'),
    ('richmond_hill', 'Richmond Hill'),
    ('ridgewood', 'Ridgewood'),
    ('rockaway_park', 'Rockaway Park'),
    ('rosedale', 'Rosedale'),
    ('south_jamaica', 'South Jamaica'),
    ('south_ozone_park', 'South Ozone Park'),
    ('springfield_gardens', 'Springfield Gardens'),
    ('st_albans', 'St. Albans'),
    ('sunnyside', 'Sunnyside'),
    ('whitestone', 'Whitestone'),
    ('woodhaven', 'Woodhaven'),
    ('woodside', 'Woodside'),
)

BROOKLYN_NEIGHBORHOODS = (
    ('bath_beach', 'Bath Beach'),
    ('bay_ridge', 'Bay Ridge'),
    ('bedford-stuyvesant', 'Bedford-Stuyvesant'),
    ('bensonhurst', 'Bensonhurst'),
    ('bergen_beach', 'Bergen Beach'),
    ('boerum_hill', 'Boerum Hill'),
    ('borough_park', 'Borough Park'),
    ('brighton_beach', 'Brighton Beach'),
    ('brooklyn_heights', 'Brooklyn Heights'),
    ('brownsville', 'Brownsville'),
    ('bushwick', 'Bushwick'),
    ('canarsie', 'Canarsie'),
    ('carroll_gardens', 'Carroll Gardens'),
    ('cobble_hill', 'Cobble Hill'),
    ('coney_island', 'Coney Island'),
    ('crown_heights', 'Crown Heights'),
    ('cypress_hills', 'Cypress Hills'),
    ('downtown_brooklyn', 'Downtown Brooklyn'),
    ('dumbo', 'Dumbo/Vinegar Hill'),
    ('dyker_heights', 'Dyker Heights'),
    ('east_new_york', 'East New York'),
    ('flatbush', 'Flatbush'),
    ('flatlands', 'Flatlands'),
    ('fort_greene', 'Fort Greene/Clinton Hill'),
    ('gerritsen_beach', 'Gerritsen Beach'),
    ('gowanus', 'Gowanus'),
    ('gravesend', 'Gravesend'),
    ('greenpoint', 'Greenpoint'),
    ('greenwood_heights', 'Greenwood Heights'),
    ('manhattan_beach', 'Manhattan Beach'),
    ('marine_park', 'Marine Park'),
    ('midwood', 'Midwood'),
    ('mill_basin', 'Mill Basin'),
    ('park_slope', 'Park Slope'),
    ('prospect_heights', 'Prospect Heights'),
    ('prospect_park_south', 'Prospect Park South/Kensington'),
    ('red_hook', 'Red Hook'),
    ('sea_gate', 'Sea Gate'),
    ('sheepshead_bay', 'Sheepshead Bay'),
    ('sunset_park', 'Sunset Park'),
    ('williamsburg', 'Williamsburg'),
    ('windsor_terrace', 'Windsor Terrace'),
)

STATENISLAND_NEIGHBORHOODS = (
    ('annadale', 'Annadale'),
    ('arden_heights', 'Arden Heights'),
    ('arrochar', 'Arrochar'),
    ('bay_street', 'Bay Street'),
    ('bulls_head', 'Bulls Head'),
    ('castleton_corners', 'Castleton Corners'),
    ('charleston', 'Charleston'),
    ('clifton', 'Clifton'),
    ('dongan_hills', 'Dongan Hills'),
    ('eltingville', 'Eltingville'),
    ('emerson_hill', 'Emerson Hill'),
    ('graniteville', 'Graniteville'),
    ('grant_city', 'Grant City'),
    ('grasmere/concord', 'Grasmere/Concord'),
    ('great_kills', 'Great Kills'),
    ('grymes_hill', 'Grymes Hill'),
    ('huguenot', 'Huguenot'),
    ('livingston', 'Livingston'),
    ('manor_heights', 'Manor Heights'),
    ('mariners_harbor', 'Mariners Harbor'),
    ('midland_beach', 'Midland Beach'),
    ('new_brighton', 'New Brighton'),
    ('new_dorp/new_dorp_beach', 'New Dorp/New Dorp Beach'),
    ('new_springville', 'New Springville'),
    ('oakwood', 'Oakwood'),
    ('pleasant_plains', 'Pleasant Plains'),
    ('port_richmond', 'Port Richmond'),
    ('princes_bay', 'Prince\'s Bay'),
    ('richmondtown', 'Richmondtown'),
    ('rosebank', 'Rosebank'),
    ('rossville', 'Rossville'),
    ('shore_acres', 'Shore Acres'),
    ('silver_lake', 'Silver Lake'),
    ('south_beach', 'South Beach'),
    ('st_george', 'St. George'),
    ('stapleton', 'Stapleton'),
    ('sunnyside', 'Sunnyside'),
    ('todt_hill', 'Todt Hill'),
    ('tompkinsville', 'Tompkinsville'),
    ('tottenville', 'Tottenville'),
    ('travis', 'Travis'),
    ('west_new_brighton', 'West New Brighton'),
    ('westerleigh', 'Westerleigh'),
    ('willowbrook', 'Willowbrook'),
    ('woodrow', 'Woodrow'),
)

NEIGHBORHOODS = (
    ('QUEENS', QUEENS_NEIGHBORHOODS),
    ('BRONX', BRONX_NEIGHBORHOODS),
    ('MANHATTAN', MANHATTAN_NEIGHBORHOODS),
    ('BROOKLYN', BROOKLYN_NEIGHBORHOODS),
    ('STATEN ISLAND', STATENISLAND_NEIGHBORHOODS),
)


DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday']

USER_TYPE = (
    ('admin', 'Admin'),
    ('agent', 'Agent'),
    ('client', 'Client')
)
