
export const ALL_FILTERS = {
    address: "",
    amenities: [],
    baths: [],
    beds: [],
    date_available: "",
    draft_listings: false,
    exclusive: false,
    hoods: [],
    lease_id: "",
    lease_status: [],
    listing_agents: [],
    listing_id: "",
    listing_type: "any",
    nofeeonly: false,
    only_active: true,
    owner_pays: false,
    pets_allowed: "any",
    price: [],
    price_per_bed: [],
    sales_agents: [],
    searching_text: "",
    size: [],
    unit: "",
    user_type: "any",
    vacant: false,
}
