# Generated by Django 2.2.3 on 2019-07-10 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0004_auto_20190629_2016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('from_to', models.CharField(choices=[('client-to-Homenet', 'Client to Homenet'), ('Homenet-to-client', 'Homenet to Client'), ('Homenet-to-agent', 'Homenet to Agent')], max_length=155)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('check', 'Check'), ('non-cash', 'Non cash')], max_length=155)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='leases.Lease')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
