# Generated by Django 2.2.3 on 2019-07-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190711_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_to',
            field=models.CharField(choices=[('client-to-Homenet', 'Client to Homenet'), ('Homenet-to-client', 'Homenet to Client'), ('Homenet-to-agent', 'Homenet to Agent')], default='client-to-Homenet', max_length=155),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('check', 'Check'), ('non-cash', 'Non cash'), ('bank', 'Bank')], default='stripe', max_length=155),
        ),
    ]
