# Generated by Django 2.2.3 on 2019-07-24 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190724_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_by_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_to',
            field=models.CharField(choices=[('client-to-Homenet', 'Client to Homenet'), ('Homenet-to-client', 'Homenet to Client'), ('Homenet-to-agent', 'Homenet to Agent')], default='client-to-Homenet', max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lease_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leases.LeaseMember'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('check', 'Check'), ('non-cash', 'Non cash'), ('bank', 'Bank')], default='stripe', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
