# Generated by Django 2.2.3 on 2019-07-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190724_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('failed', 'failed'), ('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
