# Generated by Django 2.2.3 on 2019-07-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('check', 'Check'), ('non-cash', 'Non cash'), ('bank', 'Bank'), ('cash', 'Cash')], default='stripe', max_length=32),
        ),
    ]
