# Generated by Django 2.2.4 on 2019-08-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20190731_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_to',
            field=models.CharField(choices=[('client-to-Homenet', 'Client to Homenet'), ('Homenet-to-client', 'Homenet to Client'), ('Homenet-to-agent', 'Homenet to Agent'), ('owner_payout', 'Owner Payout')], default='client-to-Homenet', max_length=64),
        ),
    ]
