# Generated by Django 2.2.4 on 2020-07-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20190807_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_to',
            field=models.CharField(choices=[('client-to-Push Forward', 'Client to Push Forward'), ('Push Forward-to-client', 'Push Forward to Client'), ('Push Forward-to-agent', 'Push Forward to Agent'), ('owner_payout', 'Owner Payout')], default='client-to-Push Forward', max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('payment_processor', 'Payment Processor'), ('check', 'Check'), ('non-cash', 'Non cash'), ('bank', 'Bank'), ('cash', 'Cash')], default='payment_processor', max_length=32),
        ),
    ]
