# Generated by Django 2.2.3 on 2019-07-16 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0006_auto_20190629_2018'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('client_email', models.CharField(blank=True, max_length=64)),
                ('client_phone', models.CharField(blank=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('listings', models.ManyToManyField(null=True, related_name='collections', to='listings.Listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
