# Generated by Django 2.2.1 on 2019-05-31 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0004_auto_20190529_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('offer', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='What would they like to pay?')),
                ('length_of_lease', models.PositiveSmallIntegerField(help_text='In months')),
                ('move_in_date', models.DateField()),
                ('op', models.PositiveSmallIntegerField(verbose_name='OP%')),
                ('total_broker_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('unsigned_unapproved', 'Unsigned, Unapproved'), ('unsigned_approved', 'Unsigned, Approved'), ('signed_approved', 'Signed, Approved'), ('client_backed_out', 'Client Backed Out'), ('cancelled', 'Cancelled'), ('awaiting_op', 'Awaiting OP'), ('pending_deletion', 'Pending Deletion')], default='unsigned_unapproved', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.Listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
