# Generated by Django 2.2.1 on 2019-05-30 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_auto_20190529_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('offer', models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='What would they like to pay?')),
                ('length_of_lease', models.PositiveSmallIntegerField(help_text='In months')),
                ('move_in_date', models.DateField()),
                ('op', models.PositiveSmallIntegerField(verbose_name='OP%')),
                ('total_broker_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
