# Generated by Django 2.2.1 on 2019-06-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_auto_20190610_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasemember',
            name='legal_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leasemember',
            name='signed_agreement',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leasemember',
            name='applicant_type',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('guarantor', 'Guarantor'), ('occupant', 'Occupant')], max_length=155),
        ),
        migrations.AlterField(
            model_name='leasemember',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leases.Lease'),
        ),
    ]
