# Generated by Django 2.2.2 on 2019-06-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_auto_20190611_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasemember',
            name='ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leasemember',
            name='user_agent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
