# Generated by Django 2.2.3 on 2019-07-09 01:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_auto_20190629_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('ssn', models.CharField(max_length=30)),
                ('driver_license', models.CharField(max_length=100, null=True)),
                ('n_of_pets', models.PositiveSmallIntegerField(null=True)),
                ('current_address', models.CharField(max_length=255, null=True)),
                ('current_monthly_rent', models.PositiveIntegerField(null=True)),
                ('landlord_name', models.CharField(max_length=100, null=True)),
                ('landlord_contact', models.CharField(max_length=100, null=True)),
                ('current_company', models.CharField(max_length=100, null=True)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('annual_income', models.CharField(max_length=100, null=True)),
                ('time_at_current_job', models.CharField(max_length=100, null=True)),
                ('lease_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leases.LeaseMember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
