# Generated by Django 2.2.3 on 2019-07-09 22:01

from django.db import migrations, models
import django.db.models.deletion
import penny.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_auto_20190709_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAppDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=penny.utils.rental_doc_path, validators=[penny.utils.validate_file_size])),
                ('rental_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.RentalApplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
