# Generated by Django 2.2.3 on 2019-07-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_rentalappdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
