# Generated by Django 2.2.4 on 2020-07-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0009_auto_20190710_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasemember',
            name='app_fee',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=15),
        ),
    ]
