# Generated by Django 2.2.4 on 2020-07-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0010_auto_20200717_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='zipcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
