# Generated by Django 2.2.4 on 2020-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0012_auto_20200729_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='zipcode',
            field=models.CharField(max_length=100, null=True, verbose_name='Zip Code'),
        ),
    ]
