# Generated by Django 2.2.4 on 2020-08-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0012_auto_20200729_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasemember',
            name='fair_housing_disclosure_ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leasemember',
            name='fair_housing_disclosure_user_agent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leasemember',
            name='nys_disclosure_ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leasemember',
            name='nys_disclosure_user_agent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leasemember',
            name='signed_fair_housing_disclosure',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leasemember',
            name='signed_nys_disclosure',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='zipcode',
            field=models.CharField(max_length=100, null=True, verbose_name='Zip Code'),
        ),
    ]
