# Generated by Django 2.2.4 on 2020-08-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0013_auto_20200806_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='aditional_income',
            field=models.CharField(max_length=150, null=True, verbose_name='Aditional sources of income'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='cell',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='current_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='current_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='current_term',
            field=models.CharField(max_length=50, null=True, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='driver_license_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='had_bankruptcy',
            field=models.BooleanField(default=False, verbose_name='Have you ever filed for bankruptcy'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='had_been_convicted',
            field=models.BooleanField(default=False, verbose_name='Have you ever been convicted of a felony'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='had_been_evicted',
            field=models.BooleanField(default=False, verbose_name='Have you ever been evicted'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='landlord_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='other_payments',
            field=models.CharField(max_length=200, null=True, verbose_name='Alimony/Child support or load payments'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='personal_reference',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='personal_reference_phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_city',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_landlord_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_landlord_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Previous landlord'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_landlord_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_state',
            field=models.CharField(max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='previous_zipcode',
            field=models.CharField(max_length=100, null=True, verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='reason_moving',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='reference_relationship',
            field=models.CharField(max_length=86, null=True, verbose_name='Relationship'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='supervisor_phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='work_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='work_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='work_supervisor',
            field=models.CharField(max_length=100, null=True, verbose_name='Supervisor'),
        ),
    ]
